/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Registrations
         * @description List users in the given status with their profiles, oldest first (admin only).
         */
        get: operations["list_registrations_admin_registrations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations/{user_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Approve a pending registration (admin only).
         *
         *     With `email_verification_required` off (the default until a sending domain
         *     exists) the account becomes active at once and can log in. When on, a 24 h
         *     verification link is issued and, in manual-mailer mode, returned so the admin
         *     can deliver it by hand. 404 when unknown, 409 when not pending.
         */
        post: operations["approve_admin_registrations__user_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations/{user_id}/reissue-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue Verification
         * @description New single-use link for an approved-but-unverified user (lost/expired link).
         */
        post: operations["reissue_verification_admin_registrations__user_id__reissue_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/registrations/{user_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Reject a pending registration (admin only); 404 when unknown, 409 when not pending.
         */
        post: operations["reject_admin_registrations__user_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stats
         * @description Input statistics for the admin dashboard (aggregates only).
         */
        get: operations["stats_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Users Overview
         * @description Per-user input statistics.
         */
        get: operations["users_overview_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Issue a JWT for an active user.
         *
         *     Wrong credentials give a generic 401; pending/rejected/unverified accounts give a 403
         *     whose code says which step is missing. Rate-limited per client address.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the caller's own account record.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description GDPR erasure: removes the account, every row and every stored object.
         */
        delete: operations["delete_me_auth_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Me
         * @description GDPR portability: profile + recordings metadata + short-lived file links.
         */
        get: operations["export_me_auth_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My Profile
         * @description Return the caller's profile columns plus consent metadata (404 without a profile).
         */
        get: operations["my_profile_auth_me_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a `pending` account with its profile; admin review follows (Q11).
         *
         *     Requires explicit consent (422 `consent_required`); the email is lower-cased and must
         *     be unique (409 `email_taken`). Rate-limited per client address.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Email
         * @description Consume a single-use verification link and move the account approved -> active.
         *
         *     The token is looked up by hash: 400 `invalid_token` when unknown, already used or
         *     expired, 400 `invalid_state` when the user is not awaiting verification.
         */
        get: operations["verify_email_auth_verify_email_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config
         * @description Environment, deployed version and the state of every feature flag (unauthenticated).
         *
         *     Public on purpose: the sign-in and application screens are flag-dependent too, and
         *     nothing here is secret - the flag names are in the frontend bundle anyway. It reads
         *     settings only, so it costs no database query (decision 0014).
         */
        get: operations["config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe reporting the deployed git SHA and environment (unauthenticated).
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Media
         * @description The catalog for this user: their items plus the official ones, newest first.
         *
         *     `kind` filters to one row of the home page; `mine=true` narrows to the user's own
         *     uploads; `tag` narrows to one library row. Ready items only - a draft has no
         *     confirmed file yet.
         *
         *     Locked items are left out unless `include_locked` asks for them, so a caller that
         *     wants something runnable gets only runnable things. The library asks for them,
         *     because showing what is coming is the point of a locked row.
         */
        get: operations["list_media_media_get"];
        put?: never;
        /**
         * Create Media
         * @description Create a catalog item (201).
         *
         *     A video must name a `source_key` from `/media/uploads` that belongs to the caller
         *     and actually exists in storage (422 otherwise), and its size counts against the
         *     quota. A game needs a `module`, a scenario a non-empty `definition`. Marking an
         *     item `official` is admin-only (403), as is creating a game or a scenario, tagging an
         *     item, or locking one: the curated catalog is editorial, not user-generated, until
         *     the sandbox exists (decision V2-0002).
         */
        post: operations["create_media_media_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign Media Upload
         * @description Step 1 of a video upload: presigned forms for the file and its optional cover.
         *
         *     413 when the user is already at their quota; the per-file cap travels inside the
         *     form, so S3 itself rejects an oversized upload.
         */
        post: operations["presign_media_upload_media_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media
         * @description One catalog item with short-lived links to its file and cover (404 if not visible).
         */
        get: operations["get_media_media__media_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Media
         * @description Delete an item and its files: the owner, or an admin for the official catalog.
         */
        delete: operations["delete_media_media__media_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{media_id}/official": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Official
         * @description Promote an item into the official catalog (admin only).
         */
        post: operations["set_official_media__media_id__official_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Expose Prometheus metrics in text format (unauthenticated, not access-logged).
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recordings
         * @description List the caller's recordings newest first; `before` paginates by `created_at`.
         */
        get: operations["list_recordings_recordings_get"];
        put?: never;
        /**
         * Upload
         * @description Proxied upload: store the file, create the recording and queue a job (202).
         *
         *     Validates cleaner, task label, extension and device (422) and streams the body
         *     through a temp file to enforce `max_upload_mb` (413) before touching S3.
         */
        post: operations["upload_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Upload
         * @description Step 2: the file is in S3; verify it and create recording + job.
         */
        post: operations["complete_upload_recordings_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Stream
         * @description Create a `stream` recording (status processing) and its empty analysis (201).
         *
         *     422 for an unknown task label or device. `ws_path` is where samples go next.
         */
        post: operations["start_stream_recordings_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Presign Upload
         * @description Step 1 of the browser upload: a direct-to-S3 form, no size-limited proxies.
         */
        post: operations["presign_upload_recordings_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recording
         * @description Return one recording with its latest job; 404 unless owned by the caller.
         */
        get: operations["get_recording_recordings__recording_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Recording
         * @description Remove the recording, its analyses and every stored artifact.
         */
        delete: operations["delete_recording_recordings__recording_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Return the latest (or the requested) analysis with its points; 404 unless owned.
         *
         *     409 `not_ready` while no analysis exists yet.
         */
        get: operations["get_analysis_recordings__recording_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download
         * @description Return a presigned GET link for the raw file; 404 unless owned and present.
         */
        get: operations["download_recordings__recording_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/neurometrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Neurometrics
         * @description Return the radius sweep of the latest (or requested) analysis; 404 unless owned.
         *
         *     409 `not_ready` when the analysis has no sweep yet - because it predates NeuroMetrics,
         *     because the recording is too short, or because the job has not run. The levels come
         *     from object storage, so the API needs no numeric dependency to serve them.
         */
        get: operations["get_neurometrics_recordings__recording_id__neurometrics_get"];
        put?: never;
        /**
         * Rebuild Neurometrics
         * @description Queue a sweep over an analysis that already has its embeddings (202).
         *
         *     This is the backfill for recordings analysed before NeuroMetrics existed; it reuses the
         *     stored vectors, so it never pays for the embedder again. 404 unless owned, 409 while a
         *     job is already active or when there is nothing to sweep.
         */
        post: operations["rebuild_neurometrics_recordings__recording_id__neurometrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reprocess
         * @description Queue a new full_pipeline job over the raw file with the given cleaner (202).
         *
         *     404 unless owned (or the raw file is missing), 422 for an unknown cleaner, 409 while
         *     a job is already queued or running. The recording drops back to `uploaded`.
         */
        post: operations["reprocess_recordings__recording_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recordings/{recording_id}/signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Signal
         * @description Return up to 30 s of the standardized or cleaned signal, decimated to `target_hz`.
         *
         *     Reads the parquet from storage; 404 unless owned, 409 before processing, 422 when
         *     `start` is past the end of the recording.
         */
        get: operations["get_signal_recordings__recording_id__signal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description The caller's sessions, newest first.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Start Session
         * @description Start a session against a visible catalog item (201).
         *
         *     Creates the live recording and its analysis, so the EEG goes to the existing
         *     websocket unchanged, and returns everything the stimulus needs to run: its
         *     manifest, its module or definition, and the `seed` a replay must reuse.
         *     404 when the item is not visible to the caller, 403 when it is locked.
         */
        post: operations["start_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description One session, with a short-lived link to its timeline once it is finished.
         */
        get: operations["get_session_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete a session, its timeline and the recording it produced.
         *
         *     The recording goes too: a session's EEG has no meaning without what was on screen.
         *     Deleting the recording is enough - the session row cascades with it - so the row is
         *     never deleted twice.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Append Events
         * @description Store one batch of stimulus events (409 once the session is closed).
         *
         *     The batch becomes a numbered part in object storage; nothing is parsed back until
         *     `finish`. 413 when the session has produced more events than a session may hold.
         */
        post: operations["append_events_sessions__session_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish Session
         * @description Close the session and assemble its timeline (409 if already closed).
         *
         *     The parts are merged into one JSONL object sorted by `t`, so a replay reads the
         *     timeline in order whatever order the batches arrived in, and the parts are then
         *     removed. A session with no events still closes: an aborted run is a fact worth
         *     keeping, and its EEG recording exists either way.
         */
        post: operations["finish_session_sessions__session_id__finish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisOut
         * @description A full trail: component versions, window geometry and points ordered by `idx`.
         */
        AnalysisOut: {
            /** Cleaner Name */
            cleaner_name: string;
            /** Cleaner Version */
            cleaner_version: string;
            /** Embedder Name */
            embedder_name: string;
            /** Embedder Version */
            embedder_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            landscape: components["schemas"]["LandscapeOut"] | null;
            /** Points */
            points: components["schemas"]["PointOut"][];
            /** Projector Meta */
            projector_meta: {
                [key: string]: unknown;
            };
            /** Projector Name */
            projector_name: string;
            /** Smooth S */
            smooth_s: number;
            /** Step S */
            step_s: number;
            /** Window S */
            window_s: number;
        };
        /**
         * ApprovalOut
         * @description Result of an admin decision; `verification_url` is set only in manual-mailer mode.
         */
        ApprovalOut: {
            user: components["schemas"]["UserOut"];
            /** Verification Url */
            verification_url?: string | null;
        };
        /** Body_upload_recordings_post */
        Body_upload_recordings_post: {
            /**
             * Cleaner
             * @default
             */
            cleaner: string;
            /**
             * Device
             * @default muse-2
             */
            device: string;
            /** File */
            file: string;
            /** Task Label */
            task_label?: string | null;
            /** Title */
            title: string;
        };
        /**
         * CompleteIn
         * @description Step 2 of the browser upload: the key from step 1 plus recording metadata.
         */
        CompleteIn: {
            /** Ble Key */
            ble_key?: string | null;
            /**
             * Cleaner
             * @default
             */
            cleaner: string;
            /**
             * Device
             * @default muse-2
             */
            device: string;
            /** Extras Key */
            extras_key?: string | null;
            /** Key */
            key: string;
            /** Task Label */
            task_label?: string | null;
            /** Title */
            title: string;
        };
        /**
         * ConfigOut
         * @description What the frontend needs to know about this deployment before anything else.
         */
        ConfigOut: {
            /** Env */
            env: string;
            /** Features */
            features: {
                /** @description Assignments, reminders and the client shell (S22). */
                assignments: boolean;
                /** @description Registration is a beta application; admin board with cohorts (S15). */
                beta_applications: boolean;
                /** @description Band power, per-block metrics, usability verdict (S20). */
                block_metrics: boolean;
                /** @description The experiment builder (S19). */
                builder: boolean;
                /** @description Operator console on the same machine (S21). */
                console: boolean;
                /** @description Remote operator console over the live relay (S23). */
                console_remote: boolean;
                /** @description Experiment model, runtime and official templates (S18). */
                experiments: boolean;
                /** @description BIDS exports (S25). */
                exports: boolean;
                /** @description The library starts every runnable item; /protocols is gone (S16). */
                library_door: boolean;
                /** @description Workspace, public and official circles; review queue (S17). */
                library_publish: boolean;
                /** @description Audio, image sets, text, questionnaires; media probe; quotas (S17). */
                library_v2: boolean;
                /** @description Locales other than English on client-facing surfaces (S26). */
                locales: boolean;
                /** @description TOTP enforced for anyone who can see another person's data (S26). */
                mfa_required: boolean;
                /** @description Recording review with annotations (S20). */
                review: boolean;
                /** @description Sessions capture EEG in the browser and upload it at finish (S16). */
                run_capture: boolean;
                /** @description Studies, participants and arms (S24). */
                studies: boolean;
                /** @description Practices and labs, invitations, subjects (S22). */
                workspaces_multi: boolean;
            };
            /** Version */
            version: string;
        };
        /**
         * DeleteMeIn
         * @description Password re-confirmation required for account self-deletion.
         */
        DeleteMeIn: {
            /** Password */
            password: string;
        };
        /**
         * DownloadOut
         * @description Short-lived presigned link to the raw file.
         */
        DownloadOut: {
            /** Expires S */
            expires_s: number;
            /** Url */
            url: string;
        };
        /**
         * EventIn
         * @description One thing the stimulus did, at `t` seconds from the start of the recording.
         */
        EventIn: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** T */
            t: number;
            /** Type */
            type: string;
        };
        /**
         * EventsIn
         * @description A batch of events, in the order the host stamped them.
         */
        EventsIn: {
            /** Events */
            events: components["schemas"]["EventIn"][];
        };
        /**
         * EventsOut
         * @description What the server has stored for this session so far.
         */
        EventsOut: {
            /** N Events */
            n_events: number;
            /** N Parts */
            n_parts: number;
        };
        /**
         * FinishIn
         * @description Close a session: the stimulus's own summary, and whether it was cut short.
         */
        FinishIn: {
            /**
             * Aborted
             * @default false
             */
            aborted: boolean;
            /** Summary */
            summary?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobOut
         * @description Latest job of a recording as exposed to its owner.
         */
        JobOut: {
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
        };
        /**
         * LandscapeOut
         * @description Just enough of a landscape projector's state to draw its terrain.
         *
         *     The full state also carries the reduction's PCA basis - hundreds of kilobytes for a
         *     512-dimensional embedder - which the browser has no use for. Only the node layout, the
         *     masses and the kernel width travel, and the field itself is evaluated client-side so
         *     the bandwidth can be a slider.
         */
        LandscapeOut: {
            /** Epsilon */
            epsilon: number;
            /** Masses */
            masses: number[];
            /** N Nodes */
            n_nodes: number;
            /** Positions */
            positions: number[][];
            /** Sigma */
            sigma: number;
            /** Stress */
            stress: number | null;
        };
        /**
         * LoginIn
         * @description Email/password credentials.
         */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MediaAccess
         * @description Whether a catalog item can actually be started, or is only advertised.
         *
         *     `locked` items are listed on purpose: the library shows what the programme will
         *     contain so a participant can see the shape of it, without pretending the content
         *     exists yet. Visibility decides *who sees* an item; access decides *who may run*
         *     one, which is why this is a separate axis from `MediaVisibility`.
         * @enum {string}
         */
        MediaAccess: "open" | "locked";
        /**
         * MediaIn
         * @description Create a catalog item.
         *
         *     Videos pass the keys returned by `/media/uploads`; games name a `module`;
         *     scenarios carry their `definition`. `manifest` is free-form but the host reads
         *     `content_warning` and `expected_duration_s` from it (decision V2-0002).
         */
        MediaIn: {
            /** @default open */
            access: components["schemas"]["MediaAccess"];
            /** Cover Key */
            cover_key?: string | null;
            /** Definition */
            definition?: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /** Duration S */
            duration_s?: number | null;
            kind: components["schemas"]["MediaKind"];
            /** Manifest */
            manifest?: {
                [key: string]: unknown;
            };
            /** Module */
            module?: string | null;
            /**
             * Official
             * @default false
             */
            official: boolean;
            /** Slug */
            slug: string;
            /** Source Key */
            source_key?: string | null;
            /** Tags */
            tags?: ("attention" | "anxiety" | "cognitive_decline")[];
            /** Title */
            title: string;
        };
        /**
         * MediaKind
         * @description What a catalog item is: an uploaded video, a mini-game, or a scripted scenario.
         *
         *     One abstraction on purpose (decision V2-0002): all three run for a while and emit
         *     timed events, so sessions, storage and replay treat them the same.
         * @enum {string}
         */
        MediaKind: "video" | "game" | "scenario";
        /**
         * MediaOut
         * @description A catalog item as the app sees it; `url` is a short-lived link for videos.
         */
        MediaOut: {
            access: components["schemas"]["MediaAccess"];
            /** Cover Url */
            cover_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /** Description */
            description: string | null;
            /** Duration S */
            duration_s: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            kind: components["schemas"]["MediaKind"];
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Mine */
            mine: boolean;
            /** Module */
            module: string | null;
            /** Slug */
            slug: string;
            status: components["schemas"]["MediaStatus"];
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            visibility: components["schemas"]["MediaVisibility"];
        };
        /**
         * MediaPresignIn
         * @description Step 1 of a video upload: the filename decides the extension.
         */
        MediaPresignIn: {
            /** Cover Filename */
            cover_filename?: string | null;
            /** Filename */
            filename: string;
        };
        /**
         * MediaPresignOut
         * @description Forms for the video and, when asked, its cover image, plus the size cap.
         */
        MediaPresignOut: {
            cover?: components["schemas"]["app__routers__media__PresignForm"] | null;
            /** Max Mb */
            max_mb: number;
            source: components["schemas"]["app__routers__media__PresignForm"];
        };
        /**
         * MediaStatus
         * @description Lifecycle of a catalog item: `draft` until its file is confirmed, then `ready`.
         * @enum {string}
         */
        MediaStatus: "draft" | "ready";
        /**
         * MediaVisibility
         * @description Who may open a catalog item.
         *
         *     `private` is the owner only - today every user upload. `official` is the curated
         *     catalog, which only an admin may create. Sharing between users comes later; the
         *     value space is here so the check never has to be rewritten.
         * @enum {string}
         */
        MediaVisibility: "private" | "official";
        /**
         * MessageOut
         * @description Minimal status acknowledgement.
         */
        MessageOut: {
            /** Status */
            status: string;
        };
        /**
         * NeuroMetricsOut
         * @description The whole radius sweep of one analysis, plus the pointers that produced it.
         *
         *     `levels` is returned entire so the UI's radius and bandwidth sliders move without a
         *     round trip; `summary` repeats the headline curves for charts that need nothing else.
         */
        NeuroMetricsOut: {
            /** Algo Name */
            algo_name: string;
            /** Algo Version */
            algo_version: string;
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Bands */
            bands: string[];
            /** Default Epsilon */
            default_epsilon: number;
            /** Default Index */
            default_index: number;
            /** Dim Reduced */
            dim_reduced: number;
            /** Epsilons */
            epsilons: number[];
            /** Levels */
            levels: {
                [key: string]: unknown;
            }[];
            /** N Points */
            n_points: number;
            /** Step S */
            step_s: number;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /**
         * PointOut
         * @description One window of the trail: time span in seconds and 2D PCA coordinates.
         */
        PointOut: {
            /** Idx */
            idx: number;
            /** Pc1 */
            pc1: number;
            /** Pc2 */
            pc2: number;
            /** T End */
            t_end: number;
            /** T Start */
            t_start: number;
        };
        /**
         * PresignIn
         * @description Step 1 of the browser upload: the file name, plus which sidecars follow.
         */
        PresignIn: {
            /** Filename */
            filename: string;
            /**
             * With Ble
             * @default false
             */
            with_ble: boolean;
            /**
             * With Extras
             * @default false
             */
            with_extras: boolean;
        };
        /**
         * PresignOut
         * @description Presigned POST form for the original file, and one per sidecar when asked.
         *
         *     `max_mb` caps the original and `extras.csv`; the raw capture has its own, larger cap
         *     in `max_ble_mb` (V2-0006).
         */
        PresignOut: {
            ble?: components["schemas"]["app__routers__recordings__PresignForm"] | null;
            extras?: components["schemas"]["app__routers__recordings__PresignForm"] | null;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Key */
            key: string;
            /** Max Ble Mb */
            max_ble_mb: number;
            /** Max Mb */
            max_mb: number;
            /** Url */
            url: string;
        };
        /**
         * ProfileIn
         * @description Demographic/brain metadata collected at registration; mirrors the Profile model.
         */
        ProfileIn: {
            /** Alcohol Use */
            alcohol_use?: string | null;
            /** Avg Sleep Hours */
            avg_sleep_hours?: number | null;
            /** Birth Year */
            birth_year: number;
            /** Caffeine Cups Per Day */
            caffeine_cups_per_day?: number | null;
            /** Education Level */
            education_level?: string | null;
            /** Full Name */
            full_name: string;
            /** Gender */
            gender?: string | null;
            /** Handedness */
            handedness: string;
            /** Hearing Issues */
            hearing_issues?: string | null;
            /** Medications */
            medications?: string | null;
            /** Meditation Practice */
            meditation_practice?: string | null;
            /** Musical Training Years */
            musical_training_years?: number | null;
            /** Native Languages */
            native_languages?: string[] | null;
            /** Neurological Conditions */
            neurological_conditions?: string | null;
            /** Nicotine Use */
            nicotine_use?: string | null;
            /** Notes */
            notes?: string | null;
            /** Occupation */
            occupation?: string | null;
            /** Psychiatric Conditions */
            psychiatric_conditions?: string | null;
            /** Sex At Birth */
            sex_at_birth: string;
            /** Vision Correction */
            vision_correction?: string | null;
        };
        /**
         * RecordingOut
         * @description Recording summary for list and detail views, with its most recent job.
         */
        RecordingOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Duration S */
            duration_s: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            job: components["schemas"]["JobOut"] | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Task Label */
            task_label: string | null;
            /** Title */
            title: string;
        };
        /**
         * RegisterIn
         * @description Registration payload; `consent` must be true and passwords are 10..200 characters.
         */
        RegisterIn: {
            /** Consent */
            consent: boolean;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            profile: components["schemas"]["ProfileIn"];
        };
        /**
         * RegistrationOut
         * @description A user awaiting review together with the profile they submitted.
         */
        RegistrationOut: {
            profile: components["schemas"]["ProfileIn"];
            user: components["schemas"]["UserOut"];
        };
        /**
         * ReprocessIn
         * @description Cleaner to use for a fresh pipeline run over an existing raw file.
         */
        ReprocessIn: {
            /**
             * Cleaner
             * @default classic
             */
            cleaner: string;
        };
        /**
         * SessionOut
         * @description A session as the app sees it; `events_url` is a short-lived link when finished.
         */
        SessionOut: {
            /** Ended At */
            ended_at: string | null;
            /** Events Url */
            events_url?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Media Id */
            media_id: string | null;
            /** Media Title */
            media_title: string;
            /** N Events */
            n_events: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Recording Id
             * Format: uuid
             */
            recording_id: string;
            /** Seed */
            seed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /**
         * SessionStartIn
         * @description Start a session against a catalog item.
         */
        SessionStartIn: {
            /**
             * Device
             * @default muse-2
             */
            device: string;
            /**
             * Media Id
             * Format: uuid
             */
            media_id: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /** Task Label */
            task_label?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * SessionStartOut
         * @description The session plus where to stream the EEG and what the stimulus needs to run.
         */
        SessionStartOut: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Definition */
            definition: {
                [key: string]: unknown;
            };
            /** Ended At */
            ended_at: string | null;
            /** Events Url */
            events_url?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /** Media Id */
            media_id: string | null;
            /** Media Title */
            media_title: string;
            /** Module */
            module: string | null;
            /** N Events */
            n_events: number;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Recording Id
             * Format: uuid
             */
            recording_id: string;
            /** Seed */
            seed: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SessionStatus"];
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Ws Path */
            ws_path: string;
        };
        /**
         * SessionStatus
         * @description Lifecycle of a stimulus session: `running` until it is closed, then `done` or `aborted`.
         * @enum {string}
         */
        SessionStatus: "running" | "done" | "aborted";
        /**
         * SignalOut
         * @description Decimated signal slice; `samples` is (n_channels, n_samples) in microvolts.
         */
        SignalOut: {
            /** Ch Names */
            ch_names: string[];
            /** Samples */
            samples: number[][];
            /** Sfreq */
            sfreq: number;
            /** Stage */
            stage: string;
            /** T0 */
            t0: number;
        };
        /**
         * StreamStartIn
         * @description Metadata of a live session, sent before the websocket is opened.
         */
        StreamStartIn: {
            /**
             * Device
             * @default muse-2
             */
            device: string;
            /** Task Label */
            task_label?: string | null;
            /** Title */
            title: string;
        };
        /**
         * StreamStartOut
         * @description Ids of the live recording/analysis and the websocket path to stream into.
         */
        StreamStartOut: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /**
             * Recording Id
             * Format: uuid
             */
            recording_id: string;
            /** Ws Path */
            ws_path: string;
        };
        /**
         * TokenOut
         * @description Bearer access token response.
         */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /**
         * UploadOut
         * @description Ids of the recording and the job created by an upload or a reprocess.
         */
        UploadOut: {
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            /**
             * Recording Id
             * Format: uuid
             */
            recording_id: string;
        };
        /**
         * UserOut
         * @description Public view of an account (no password hash).
         */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Email Verified At */
            email_verified_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * PresignForm
         * @description A presigned POST: where to send the file and the fields that must ride along.
         */
        app__routers__media__PresignForm: {
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
        /**
         * PresignForm
         * @description One presigned POST form the browser submits straight to S3.
         */
        app__routers__recordings__PresignForm: {
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Key */
            key: string;
            /** Url */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_registrations_admin_registrations_get: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_admin_registrations__user_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reissue_verification_admin_registrations__user_id__reissue_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_admin_registrations__user_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    users_overview_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    delete_me_auth_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteMeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_auth_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    my_profile_auth_me_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_auth_verify_email_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_media_media_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["MediaKind"] | null;
                mine?: boolean | null;
                tag?: ("attention" | "anxiety" | "cognitive_decline") | null;
                include_locked?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_media_media_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_media_upload_media_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MediaPresignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaPresignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_media__media_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_official_media__media_id__official_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_recordings_recordings_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_recordings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_recordings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_recordings_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_stream_recordings_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_upload_recordings_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recording_recordings__recording_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_recordings__recording_id__analysis_get: {
        parameters: {
            query?: {
                analysis_id?: string | null;
            };
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_recordings__recording_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_neurometrics_recordings__recording_id__neurometrics_get: {
        parameters: {
            query?: {
                analysis_id?: string | null;
            };
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeuroMetricsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebuild_neurometrics_recordings__recording_id__neurometrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_recordings__recording_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReprocessIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_signal_recordings__recording_id__signal_get: {
        parameters: {
            query?: {
                start?: number;
                duration?: number;
                stage?: string;
                target_hz?: number;
            };
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStartOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    append_events_sessions__session_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finish_session_sessions__session_id__finish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinishIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
