/**
 * API response types.
 *
 * Recordings, media and sessions come from the backend's OpenAPI contract
 * (`api-types.ts`, generated by `npm run api:types`); the rest are still written by hand
 * and move to generated types as each area is touched (plan V3, "Contracts").
 */
import type { components } from "@/lib/api-types";

type Schemas = components["schemas"];

/** Latest job of a recording. */
export type RecordingJob = Schemas["JobOut"];

/** A recording summary, as `GET /recordings` and `GET /recordings/{id}` return it. */
export type Recording = Schemas["RecordingOut"];

export interface TrailPoint {
  idx: number;
  t_start: number;
  t_end: number;
  pc1: number;
  pc2: number;
}

export interface Analysis {
  id: string;
  cleaner_name: string;
  cleaner_version: string;
  embedder_name: string;
  embedder_version: string;
  window_s: number;
  step_s: number;
  smooth_s: number;
  /** Which projector drew the trail: "ballmapper-landscape" or the older "pca". */
  projector_name: string;
  projector_meta: {
    /** PCA only: the share of variance the two axes hold. */
    ratio?: [number, number] | null;
    cleaner_notes?: string[] | null;
  };
  /** Present only for a landscape projection: the terrain the trail is drawn on. */
  landscape: AnalysisLandscape | null;
  points: TrailPoint[];
}

/** The node layout the browser needs to draw a landscape's density field. */
export interface AnalysisLandscape {
  epsilon: number;
  n_nodes: number;
  /** MDS stress-1: how faithfully the layout holds the cover's distances. */
  stress: number | null;
  sigma: number;
  positions: [number, number][];
  masses: number[];
}

export interface SignalPreview {
  stage: string;
  sfreq: number;
  ch_names: string[];
  t0: number;
  samples: number[][];
}

export interface UserInfo {
  id: string;
  email: string;
  role: string;
  status: string;
  created_at: string;
  email_verified_at: string | null;
}

export const TASK_LABELS = [
  "rest_eyes_open",
  "rest_eyes_closed",
  "meditation",
  "breathing_exercise",
  "mental_arithmetic",
  "reading",
  "music_listening",
  "memory_recall",
  "motor_imagery",
  "video_watching",
] as const;

/**
 * The library's browsing rows, in the order they are shown.
 *
 * Closed list, mirrored from the backend's `MEDIA_TAGS` (which enforces it with a CHECK
 * constraint): tags are the top-level navigation, so a typo would silently produce an
 * empty row rather than an error.
 */
export const MEDIA_TAGS = [
  "attention",
  "anxiety",
  "cognitive_decline",
] as const;

export type MediaTag = (typeof MEDIA_TAGS)[number];

export const MEDIA_TAG_LABELS: Record<MediaTag, string> = {
  attention: "Attention",
  anxiety: "Anxiety",
  cognitive_decline: "Cognitive Decline",
};

/** One line under each row title, saying what the tag is for. */
export const MEDIA_TAG_HINTS: Record<MediaTag, string> = {
  attention:
    "Hold a target, ignore the rest, and stop a response you already started.",
  anxiety: "Settle the body, then watch what the signal does with it.",
  cognitive_decline:
    "Memory, speed and flexibility, measured the same way each time.",
};

/**
 * The manifest fields the host reads before starting an item (backend V2-0002). The API
 * types the manifest as an open object, so the fields the app relies on are named here.
 */
export interface MediaManifest {
  content_warning?: string | null;
  expected_duration_s?: number;
}

/** A catalog item: something a session can be recorded against (backend V2-0002). */
export type Media = Omit<Schemas["MediaOut"], "manifest"> & {
  manifest: MediaManifest;
};

/**
 * An item's access level, `open` when the API does not report one.
 *
 * The generated type says the field is always there, but the two repos deploy
 * separately: a frontend ahead of its API once received items without `access` and
 * `tags` and took the library down with a `TypeError`. Failing open is safe here - the
 * field only decides what the library draws; the backend refuses to start a locked item.
 */
export function mediaAccess(item: Media): "open" | "locked" {
  return (item as Partial<Media>).access ?? "open";
}

/** An item's browsing tags, empty when the API does not report them (see above). */
export function mediaTags(item: Media): string[] {
  return (item as Partial<Media>).tags ?? [];
}
